[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.74.1",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.8",
    "python-dotenv>=1.2.1",
    "streamlit>=1.51.0",
]
